---
- name: place working copy of gitolite-admin repo
  git: 
    repo: /var/lib/gitolite3/repositories/gitolite-admin.git
    dest: /tmp/gitolite-admin
    force: yes

- name: Configure admin users and conf/conf.d
  template:
   src: gitolite.conf.j2
   dest: /tmp/gitolite-admin/conf/gitolite.conf

- name: Verify conf/conf.d location
  file:
    path: /tmp/gitolite-admin/conf/conf.d
    state: directory

# We need to add something here because git won't save empty 
# folders and a README seems safe. 
- name: Verify README
  copy:
    src: README
    dest: /tmp/gitolite-admin/conf/conf.d/README
            
- name: install user ssh pubkey files
  copy:
    dest: "/tmp/gitolite-admin/keydir/{{ item.name }}.pub"
    content: "{{ item.pubkey }}"
  with_items: "{{ gitolite_users }}"

- name: save configuration
  shell: |
          git add .
          git commit -m "Ansible updated config to match role settings."
          gitolite push --all
  args:
    chdir: /tmp/gitolite-admin

        
