---

- name: create dummy admin key
  shell: ssh-keygen -q -f /var/lib/gitolite3/.ssh/gitadmin -P  "$(</dev/urandom tr -dc _A-Z-a-z-0-9 | head -c64)"
  args:
    creates: /var/lib/gitolite3/.ssh/gitadmin
- name: initialize empty gitolite-admin repo
  shell: gitolite setup -pk /var/lib/gitolite3/.ssh/gitadmin.pub
  args:
    creates: /var/lib/gitolite2/repositories/gitolite-admin.git/HEAD
